### ISSUE TITLE
Couldnt find the pointlight memory pool

### ISSUE THREAD

**Issue by bythehist** [etra0/litcher#15]
<img width="598" alt="Screenshot 2023-06-06 160407" src="https://github.com/etra0/litcher/assets/124395280/6f35c870-a5dc-4acc-87e6-a1bcccf97a77">

getting this error when trying to use litcher w/ admin permissions

**Comment by etra0** [comment]
Oh, you're right, it seems the part where I was getting the pointers was changed... ugh, annoying.

Thanks for the report, I'll work on this.

**Comment by etra0** [comment]
I just updated the code to find the new pointers for the version [v0.3.6](https://github.com/etra0/litcher/releases/tag/v0.3.6), let me know how it goes!

**Comment by bythehist** [comment]
Yep! Everything looks good on my end! Was able to load up and place lights. Thank you so much! I appreciate you! Still crashes when I run HAGs and reshade, but I don't really need to use hags anymore (was just using it for frame generation), now that their dlss2 is fixed up a bit and I can get some solid frames with it. Once again you have my thanks!!!

**Comment by etra0** [comment]
I don't know what HAGs are, but I'd be worried if you couldn't use Reshade and LITcher at the same time. I suspect that it could be some bug related to one of my dependencies (hudhook) but it would be rather hard to fix since I cannot use DLSS3. 

Are you simply not being able to use both tools (and only these two) without DLSS3? To create an issue and investigate.

**Comment by bythehist** [comment]
Hello! Long time no talk, sorry to leaving you hanging for months! I stopped playing for the time being so sorry for the delay. I thought maybe waiting until a new patch may fix it. I can use both tools without DLSS 3 frame generation yes. But would like to use frame generation, and thats when I get the crash. I've attached the crash dump here. Please let me know if you need any more info. ty

[Witcher_Crash_Dump.zip](https://github.com/etra0/litcher/files/12834669/Witcher_Crash_Dump.zip)

**Comment by etra0** [comment]
Hi, I'm afraid I cannot help you since i don't have hardware compatible with dlss 3.5 so there's no way for me to improve the situation.

**Comment by bythehist** [comment]
No worries! Thank you for getting back to me, I appreciate it.
